PRAGMA foreign_keys = OFF;

CREATE TABLE invoices__new (
  id TEXT PRIMARY KEY NOT NULL,
  invoice_number TEXT NOT NULL,
  type TEXT NOT NULL,
  client_id TEXT,
  client_name TEXT,
  date TEXT NOT NULL,
  items TEXT,
  total_amount REAL NOT NULL,
  discount REAL,
  original_amount REAL,
  exchange_rate REAL,
  paid_amount REAL NOT NULL,
  remaining_amount REAL NOT NULL,
  payment_type TEXT,
  apply_stock INTEGER DEFAULT 1,
  currency TEXT,
  notes TEXT,
  return_type TEXT,
  created_by_id TEXT,
  created_by_name TEXT,
  created_by_role TEXT,
  geo_lat REAL,
  geo_lng REAL,
  geo_label TEXT,
  target_warehouse_id TEXT,
  target_warehouse_name TEXT,
  journal_entry_id INTEGER,
  created_at TEXT DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (journal_entry_id) REFERENCES journal_entries(id) ON UPDATE NO ACTION ON DELETE NO ACTION
);

INSERT INTO invoices__new (
  id,
  invoice_number,
  type,
  client_id,
  client_name,
  date,
  items,
  total_amount,
  discount,
  original_amount,
  exchange_rate,
  paid_amount,
  remaining_amount,
  payment_type,
  apply_stock,
  currency,
  notes,
  return_type,
  created_by_id,
  created_by_name,
  created_by_role,
  geo_lat,
  geo_lng,
  geo_label,
  target_warehouse_id,
  target_warehouse_name,
  journal_entry_id,
  created_at
)
SELECT
  id,
  invoice_number,
  type,
  client_id,
  client_name,
  date,
  items,
  total_amount,
  discount,
  original_amount,
  exchange_rate,
  paid_amount,
  remaining_amount,
  payment_type,
  apply_stock,
  currency,
  notes,
  return_type,
  created_by_id,
  created_by_name,
  created_by_role,
  geo_lat,
  geo_lng,
  geo_label,
  target_warehouse_id,
  target_warehouse_name,
  journal_entry_id,
  created_at
FROM invoices;

DROP TABLE invoices;
ALTER TABLE invoices__new RENAME TO invoices;

PRAGMA foreign_keys = ON;
